apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark-apps
spec:
  type: Scala
  mode: cluster
  image: gcr.io/spark-operator/spark:v3.1.1
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar
  sparkVersion: 3.1.1
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    #serviceAccount: spark
    labels: {}  # Required to avoid KeyError in Airflow
  executor:
    cores: 1
    instances: 2
    memory: 512m
    labels: {}  # Optional but consistent
